"use client";
import { Ticket } from "@/types/types";
import Image from "next/image";
import React from "react";

interface TicketViewProps {
  ticket: Ticket;
  sellerName: string;
}

export default function TicketView({ ticket, sellerName }: TicketViewProps) {
  const ticketImageUrl =
    "https://storage.googleapis.com/gemini-prod-us-west1-409902-421713/uploaded/WhatsApp%20Image%202025-08-13%20at%2010.36.04%20PM.jpeg-b841bfb8-760a-42ca-92de-4226f51da301";
  const purchaseDate = new Date(ticket.purchase_date);
  const formattedDate = purchaseDate.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
  const formattedTime = purchaseDate.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });

  const handlePrint = () => window.print();

  return (
    <div className="bg-gray-100 p-4">
      <div
        className="ticket-container relative w-full max-w-2xl mx-auto font-sans"
        style={{ aspectRatio: "1200 / 628" }}
      >
        <Image
          src={ticketImageUrl}
          alt="Naga Food Fest Ticket Background"
          className="w-full h-full object-cover rounded-lg shadow-lg"
        />
        <div className="absolute inset-0 text-black">
          <div
            className="absolute text-center"
            style={{ top: "10%", right: "9%", transform: "translate(0, -50%)" }}
          >
            <p className="text-2xl md:text-4xl lg:text-5xl font-extrabold tracking-wider">
              {ticket.id}
            </p>
          </div>
          <div
            className="absolute text-center"
            style={{
              top: "56%",
              left: "50%",
              transform: "translate(-50%, -50%)",
              width: "50%",
            }}
          >
            <p className="text-xs md:text-sm text-gray-800 font-semibold mb-1">
              Purchased By:
            </p>
            <p className="text-lg md:text-2xl font-bold break-words">
              {ticket.purchaser_name}
            </p>
          </div>
          <div
            className="absolute text-center"
            style={{
              top: "65%",
              left: "50%",
              transform: "translate(-50%, -50%)",
            }}
          >
            <p className="text-xs md:text-sm font-semibold">
              {formattedDate} at {formattedTime}
            </p>
          </div>
          <div
            className="absolute text-center"
            style={{
              top: "72%",
              left: "50%",
              transform: "translate(-50%, -50%)",
            }}
          >
            <p className="text-xs md:text-sm text-gray-800 font-semibold">
              Generated by: {sellerName}
            </p>
          </div>
        </div>
      </div>
      <div className="text-center mt-6 print-hidden">
        <button
          onClick={handlePrint}
          className="px-8 py-3 bg-blue-600 text-white font-bold rounded-lg shadow-md hover:bg-blue-700"
        >
          Print / Save as PDF
        </button>
      </div>
      <style>{`
                @media print {
                    body * { visibility: hidden; }
                    .print-hidden { display: none; }
                    .ticket-container, .ticket-container * { visibility: visible; }
                    .ticket-container { position: absolute; left: 0; top: 0; width: 100%; }
                }
            `}</style>
    </div>
  );
}
