"use client";
import React, { useState, useMemo, useTransition } from "react";
import ConfirmationDialog from "./ConfirmationDialog";
import { Ticket, User } from "@/types/types";
import StatusBadge from "./StatusBadge";
import { redeemTicket } from "@/app/actions";

interface ValidatorDashboardProps {
  user: User;
  tickets: Ticket[];
}

// --- TicketList Component (Moved outside) ---
const TicketList = ({
  ticketList,
  onRedeem,
}: {
  ticketList: Ticket[];
  onRedeem: (ticket: Ticket) => void;
}) => (
  <div className="space-y-3">
    {ticketList.map((ticket) => (
      <div
        key={ticket.id}
        className="bg-white p-4 rounded-lg shadow-md flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4"
      >
        <div className="flex-1">
          <p className="font-extrabold text-xl text-gray-900">{ticket.id}</p>
          <p className="text-gray-800 text-lg">
            Purchaser:{" "}
            <span className="font-semibold">{ticket.purchaser_name}</span>
          </p>
          <p className="text-gray-600">
            Seller:{" "}
            <span className="font-semibold">{ticket.generated_by_name}</span>
          </p>
          <p className="text-xs text-gray-500">
            Purchased: {new Date(ticket.purchase_date).toLocaleString()}
          </p>
        </div>
        <div className="flex flex-col items-stretch sm:items-end gap-3 w-full sm:w-auto">
          <StatusBadge status={ticket.status} />
          {ticket.status === "VALID" && (
            <button
              onClick={() => onRedeem(ticket)}
              className="w-full bg-green-600 text-white font-bold py-3 px-6 rounded-lg hover:bg-green-700 shadow-lg cursor-pointer"
            >
              REDEEM
            </button>
          )}
        </div>
      </div>
    ))}
  </div>
);

export default function ValidatorDashboard({
  user,
  tickets,
}: ValidatorDashboardProps) {
  // Removed unused supabase client initialization
  const [searchTerm, setSearchTerm] = useState<string>("");
  const [showConfirm, setShowConfirm] = useState<Ticket | null>(null);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  const filteredTickets = useMemo(() => {
    if (!searchTerm.trim()) return tickets.slice(0, 10);
    const lowerCaseSearch = searchTerm.toLowerCase();
    return tickets.filter(
      (t) =>
        t.id.toLowerCase().includes(lowerCaseSearch) ||
        t.purchaser_name.toLowerCase().includes(lowerCaseSearch) ||
        t.generated_by_name.toLowerCase().includes(lowerCaseSearch)
    );
  }, [searchTerm, tickets]);

  const handleRedeem = () => {
    if (!showConfirm) return;
    setError(null);
    startTransition(async () => {
      const result = await redeemTicket(showConfirm.id);
      if (result.error) {
        setError(result.error);
      }
      setShowConfirm(null); // Close the dialog
    });
  };

  const handleDownloadReport = () => {
    const headers = [
      "ID",
      "Purchaser Name",
      "Purchase Date",
      "Status",
      "Generated By",
    ];
    const csvRows = [
      headers.join(","),
      ...tickets.map((t) =>
        [
          t.id,
          `"${t.purchaser_name}"`,
          new Date(t.purchase_date).toLocaleString(),
          t.status,
          `"${t.generated_by_name}"`,
        ].join(",")
      ),
    ];

    const csvString = csvRows.join("\n");
    const blob = new Blob([csvString], { type: "text/csv;charset=utf-8;" });
    const link = document.createElement("a");
    const url = URL.createObjectURL(blob);
    link.setAttribute("href", url);
    link.setAttribute("download", "naga_food_fest_report.csv");
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="p-4 space-y-6">
      <div className="bg-white p-6 rounded-xl shadow-lg">
        <h2 className="text-2xl font-bold text-gray-800 mb-4">
          Validate Tickets
        </h2>
        <input
          type="text"
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full px-4 py-3 border border-gray-300 rounded-lg text-lg"
          placeholder="Search by ID, Purchaser, or Seller..."
        />
        {user.role === "admin" && (
          <div className="mt-4 text-center">
            <button
              onClick={handleDownloadReport}
              className="inline-flex items-center gap-2 px-6 py-2 bg-gray-700 text-white font-bold rounded-lg shadow-md hover:bg-gray-800"
            >
              Download Full Report
            </button>
          </div>
        )}
      </div>

      <div>
        <h3 className="text-xl font-bold text-gray-700 mb-3">
          {searchTerm ? "Search Results" : "Recent Tickets"}
        </h3>
        {error && <p className="text-red-500 text-sm mb-2">{error}</p>}
        <TicketList ticketList={filteredTickets} onRedeem={setShowConfirm} />
      </div>

      {showConfirm && (
        <ConfirmationDialog
          message={`Confirm redemption for ticket ${showConfirm.id}?`}
          onConfirm={handleRedeem}
          onCancel={() => setShowConfirm(null)}
          isConfirming={isPending}
        />
      )}
    </div>
  );
}
